apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-1
  template:
    metadata:
      labels:
        app: my-app-1
    spec:
      containers:
      - name: my-container
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-pvc-mount
          mountPath: /data
      volumes:
      - name: my-pvc-mount
        persistentVolumeClaim:
          claimName: test-pvc-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-1
  namespace: test-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
---
